all:
  children:
    network_devices:
      children:
        site1:
          children:
            routers:
              hosts:
                CRT1:
                  ansible_host: 200.0.0.1
                CRT2:
                  ansible_host: 200.0.0.2
                CRT3:
                  ansible_host: 200.0.0.3
            switches:

              hosts:
                DWS1:
                   ansible_host: 200.0.0.6
                DSW2:
                   ansible_host: 200.0.0.7
        site2:
          children:
            routers:
              hosts:
                CRT4:
                  ansible_host: 200.0.0.4
                CRT5:
                  ansible_host: 200.0.0.5
            switches:
              hosts:
                DSW3:
                  ansible_host: 200.0.0.8
                DSW4:
                  ansible_host: 200.0.0.9


